-- =====================================================
-- SEED SCRIPT: Neuropsychological Test Templates
-- =====================================================
-- Description: Inserts 8 complete neuropsychological assessment tests
-- Source: escalas.pdf.pdf
-- Date: 2025-01-06
-- =====================================================

-- Test 1: EPF-TDAH - Escala de Prejuízos Funcionais TDAH
INSERT INTO testes_templates (nome, sigla, descricao, tipo, versao, faixa_etaria_min, faixa_etaria_max, publico, ativo, configuracao, perguntas)
VALUES (
  'EPF-TDAH - Escala de Prejuízos Funcionais TDAH',
  'EPF-TDAH',
  'Escala composta por frases que descrevem prejuízos que adultos podem vivenciar no cotidiano em função de desatenção, esquecimento, agitação, impulsividade, falta de planejamento, descontrole das emoções e descontrole de raiva.',
  'escala_likert',
  '1.0',
  18,
  NULL,
  true,
  true,
  '{
    "escala_min": 0,
    "escala_max": 4,
    "opcoes": ["Não se aplica (NA)", "Nunca (N)", "Raramente (R)", "Algumas vezes (AV)", "Muitas vezes (MV)", "Sempre (S)"],
    "pontuacao_opcoes": {"0": 0, "1": 0, "2": 1, "3": 2, "4": 3, "5": 4},
    "gabarito": {},
    "interpretacao": {
      "minimo": 0,
      "maximo": 264,
      "categorias": [
        {"min": 0, "max": 88, "nivel": "Baixo", "descricao": "Prejuízos funcionais baixos"},
        {"min": 89, "max": 176, "nivel": "Moderado", "descricao": "Prejuízos funcionais moderados"},
        {"min": 177, "max": 264, "nivel": "Alto", "descricao": "Prejuízos funcionais altos"}
      ]
    }
  }'::jsonb,
  ARRAY[
    'Meus trabalhos foram de baixa qualidade.',
    'Fui reprovado.',
    'Meus professores e/ou colegas deixaram de confiar em mim.',
    'Fiquei estressado por deixar as tarefas para a última hora.',
    'Deixei cursos inacabados.',
    'Obtive notas baixas.',
    'Gastei mais tempo para concluí-los.',
    'Percebi variações em meu desempenho.',
    'As pessoas ficaram insatisfeitas com o meu desempenho.',
    'Fui repreendido pelo meu superior.',
    'Perdi oportunidades.',
    'Me senti fracassado.',
    'Me senti inseguro.',
    'As pessoas deixaram de confiar em mim.',
    'Fui demitido.',
    'Ocupei cargo abaixo do meu potencial.',
    'A minha carreira ficou parada.',
    'As minhas relações com os colegas de trabalho foram conflituosas.',
    'O meu parceiro precisou assumir responsabilidades que eram minhas.',
    'Os términos foram precipitados.',
    'Recebi queixas sobre o meu modo de ser.',
    'Vivenciei conflitos com o meu companheiro.',
    'Pequenos desentendimentos ganharam uma grande proporção.',
    'Meu parceiro ficou insatisfeito comigo.',
    'Senti-me entediado.',
    'Tive dificuldade em manter relações duradouras.',
    'Os ambientes ficaram bagunçados por um grande período de tempo.',
    'Meus familiares ficaram chateados pelo meu modo de ser.',
    'Ocorreram pequenos acidentes (por exemplo, esqueci a panela no fogo, me cortei).',
    'Senti-me incapaz para realizar os afazeres domésticos.',
    'Vivenciei conflitos com meus familiares.',
    'Perdi o prazo de garantia de eletrodomésticos que precisavam de troca ou reparo.',
    'Fui chamado de irresponsável.',
    'As pessoas se afastaram de mim.',
    'Me senti inseguro.',
    'Fui chamado de enrolado.',
    'Fui considerado inconveniente.',
    'Tive dificuldade em manter amizades duradouras.',
    'Passei uma impressão de descaso.',
    'Vivenciei conflitos com as pessoas.',
    'As pessoas ficaram chateadas comigo.',
    'Fui considerado antipático.',
    'Tive gastos desnecessários.',
    'Fiquei endividado.',
    'Tive algum serviço cortado/suspenso por falta de pagamento.',
    'Dependi de alguém para controlar minhas finanças.',
    'Tive prejuízos financeiros.',
    'Tive restrição de crédito.',
    'Tive meu nome incluído em algum cadastro (SERASA, SPC) em função de dívidas.',
    'Tive horários de alimentação desregulados.',
    'Adoeci por falta de prevenção.',
    'A minha rotina de sono foi alterada.',
    'Fiquei sedentário.',
    'Tive doenças agravadas por falta de cuidado.',
    'Tive problemas com álcool, cigarro e/ou drogas.',
    'As pessoas se sentiram inseguras em andar comigo enquanto eu dirigia o carro.',
    'Me envolvi em acidentes.',
    'Recebi multas de trânsito.',
    'Coloquei-me em situações de risco.',
    'Me envolvi em conflitos com outros motoristas quando dirigia meu carro.',
    'Meu veículo ficou exposto a danos e desgastes mecânicos.',
    'Vivenciei momentos difíceis por destacar figuras de autoridade (como policiais, professores ou eu chefe).',
    'Me envolvi em situações graves em que poderia ter sido preso.',
    'Me expus a situações perigosas ao fazer uso e/ou transportar substâncias ilícitas.',
    'Com o risco de ser processado por estranher, insultar e/ou humilhar outra pessoa.',
    'Com o risco de ser processado por agredir outra pessoa.'
  ]
);

-- Test 2: AQ - Quociente Autism-Spectrum
INSERT INTO testes_templates (nome, sigla, descricao, tipo, versao, faixa_etaria_min, faixa_etaria_max, publico, ativo, configuracao, perguntas)
VALUES (
  'AQ - Quociente Autism-Spectrum',
  'AQ',
  'O Quociente Autism-Spectrum, ou AQ, é uma medida do grau de traços Autísticos em adultos. Este teste não é um autodiagnóstico, tem o objetivo de ajudar a identificar alguns traços que podem estar ligados ao comportamento autista.',
  'multipla_escolha',
  '1.0',
  18,
  NULL,
  true,
  true,
  '{
    "opcoes": ["Concordo definitivamente", "Concordo um pouco", "Discordo um pouco", "Discordo definitivamente"],
    "gabarito": {
      "0": {"resposta_correta": [2, 3], "pontuacao": 1},
      "1": {"resposta_correta": [0, 1], "pontuacao": 1},
      "2": {"resposta_correta": [0, 1], "pontuacao": 1},
      "3": {"resposta_correta": [0, 1], "pontuacao": 1},
      "4": {"resposta_correta": [2, 3], "pontuacao": 1},
      "5": {"resposta_correta": [3], "pontuacao": 1},
      "6": {"resposta_correta": [0, 1], "pontuacao": 1},
      "7": {"resposta_correta": [0, 1], "pontuacao": 1},
      "8": {"resposta_correta": [0, 1], "pontuacao": 1},
      "9": {"resposta_correta": [2, 3], "pontuacao": 1},
      "10": {"resposta_correta": [2, 3], "pontuacao": 1},
      "11": {"resposta_correta": [0, 1], "pontuacao": 1},
      "12": {"resposta_correta": [2, 3], "pontuacao": 1},
      "13": {"resposta_correta": [0, 1], "pontuacao": 1},
      "14": {"resposta_correta": [0, 1], "pontuacao": 1},
      "15": {"resposta_correta": [2, 3], "pontuacao": 1},
      "16": {"resposta_correta": [2, 3], "pontuacao": 1},
      "17": {"resposta_correta": [0, 1], "pontuacao": 1},
      "18": {"resposta_correta": [3], "pontuacao": 1},
      "19": {"resposta_correta": [3], "pontuacao": 1},
      "20": {"resposta_correta": [2, 3], "pontuacao": 1},
      "21": {"resposta_correta": [3], "pontuacao": 1},
      "22": {"resposta_correta": [0, 1], "pontuacao": 1},
      "23": {"resposta_correta": [2, 3], "pontuacao": 1},
      "24": {"resposta_correta": [0, 1], "pontuacao": 1},
      "25": {"resposta_correta": [2, 3], "pontuacao": 1},
      "26": {"resposta_correta": [0, 1], "pontuacao": 1},
      "27": {"resposta_correta": [2, 3], "pontuacao": 1},
      "28": {"resposta_correta": [2, 3], "pontuacao": 1},
      "29": {"resposta_correta": [2, 3], "pontuacao": 1},
      "30": {"resposta_correta": [2, 3], "pontuacao": 1},
      "31": {"resposta_correta": [2, 3], "pontuacao": 1},
      "32": {"resposta_correta": [0, 1], "pontuacao": 1},
      "33": {"resposta_correta": [3], "pontuacao": 1},
      "34": {"resposta_correta": [0, 1], "pontuacao": 1},
      "35": {"resposta_correta": [2, 3], "pontuacao": 1},
      "36": {"resposta_correta": [0, 1], "pontuacao": 1},
      "37": {"resposta_correta": [0, 1], "pontuacao": 1},
      "38": {"resposta_correta": [2, 3], "pontuacao": 1},
      "39": {"resposta_correta": [2, 3], "pontuacao": 1},
      "40": {"resposta_correta": [2, 3], "pontuacao": 1},
      "41": {"resposta_correta": [3], "pontuacao": 1},
      "42": {"resposta_correta": [0, 1], "pontuacao": 1},
      "43": {"resposta_correta": [2, 3], "pontuacao": 1},
      "44": {"resposta_correta": [0, 1], "pontuacao": 1},
      "45": {"resposta_correta": [2, 3], "pontuacao": 1},
      "46": {"resposta_correta": [2, 3], "pontuacao": 1},
      "47": {"resposta_correta": [0, 1], "pontuacao": 1},
      "48": {"resposta_correta": [2, 3], "pontuacao": 1},
      "49": {"resposta_correta": [0, 1], "pontuacao": 1}
    },
    "interpretacao": {
      "minimo": 0,
      "maximo": 50,
      "categorias": [
        {"min": 0, "max": 25, "nivel": "Baixo", "descricao": "Poucos traços autísticos"},
        {"min": 26, "max": 31, "nivel": "Limítrofe", "descricao": "Possíveis traços autísticos"},
        {"min": 32, "max": 50, "nivel": "Alto", "descricao": "Traços autísticos significativos"}
      ]
    }
  }'::jsonb,
  ARRAY[
    'Eu prefiro fazer as coisas com os outros, em vez de sozinho.',
    'Eu prefiro fazer as coisas da mesma maneira sempre.',
    'Se eu tentar imaginar algo, acho que é muito fácil criar uma imagem em minha mente.',
    'Eu frequentemente fico tão fortemente concentrado em uma coisa que eu ignoro outras coisas.',
    'Costumo observar pequenos sons quando os outros não os percebem.',
    'Eu costumo observar placas de carros, números ou sequências similares de informações.',
    'Outras pessoas frequentemente me corrigem, dizendo que o que falo é falta de educação, mesmo quando eu acho que é educado.',
    'Quando eu estou lendo uma história, eu posso facilmente imaginar o que os personagens estão fazendo.',
    'Sou fascinado por datas.',
    'Em um grupo social, eu posso facilmente manter conversação com diferentes pessoas.',
    'Acho fácil conviver socialmente.',
    'Eu percebo detalhes que outros não percebem tão facilmente.',
    'Prefiro ir a uma biblioteca do que uma festa.',
    'Acho inventar histórias algo muito fácil.',
    'Sou atraído mais fortemente para as pessoas do que para coisas.',
    'Quando tenho interesse muito forte num determinado assunto, fico muito chateado se não consigo levar adiante meus pensamentos sobre este assunto.',
    'Eu gosto de fofoca social.',
    'Quando eu falo, nem sempre é fácil para os outros entenderem claramente o que quero dizer.',
    'Sou fascinado por números.',
    'Quando eu estou lendo uma história, acho difícil entender as intenções dos personagens.',
    'Eu particularmente não gosto de ler ficção.',
    'Acho que é difícil fazer novos amigos.',
    'Percebo padrões nas coisas o tempo todo.',
    'Prefiro ir ao teatro do que um museu.',
    'Eu não me chateio se minha rotina diária é perturbada.',
    'Eu frequentemente tenho dificuldade em manter uma conversa.',
    'Consigo facilmente "ler nas entrelinhas" quando alguém está falando comigo.',
    'Eu costumo me concentrar mais numa imagem por inteiro do que nos pequenos detalhes.',
    'Eu não sou muito bom em lembrar números de telefone.',
    'Eu não costumo perceber pequenas mudanças em uma situação ou na aparência de uma pessoa.',
    'Eu percebo se alguém que está me ouvindo está ficando entediado.',
    'Acho fácil fazer mais de uma coisa ao mesmo tempo.',
    'Quando eu falo ao telefone, tenho dificuldade de saber quando é a minha vez de falar.',
    'Eu gosto de fazer as coisas de forma espontânea.',
    'Muitas vezes sou o último a entender uma piada.',
    'Consigo perceber o que uma pessoa está pensando ou sentindo só de olhar para seu rosto.',
    'Se houver uma interrupção, eu posso voltar para o que eu estava fazendo muito rapidamente.',
    'Eu sou bom em conversa social.',
    'Muitas vezes as pessoas me dizem que eu continuo falando repetidamente sobre a mesma coisa.',
    'Quando eu era jovem, eu gostava de jogar jogos de imaginação com outras crianças.',
    'Eu gosto de coletar informações sobre categorias de coisas (por exemplo, os tipos de carros, pássaros, trens, plantas).',
    'Para mim, é muito difícil imaginar-me sendo outra pessoa.',
    'Eu gosto de planejar cuidadosamente qualquer atividade que eu irei participar.',
    'Gosto de ocasiões (reuniões) sociais.',
    'Acho difícil detectar as reais intenções das pessoas.',
    'Situações novas me deixam ansioso.',
    'Eu gosto de conhecer novas pessoas.',
    'Eu sou um bom diplomata.',
    'Eu não sou muito bom em lembrar da data de nascimento das pessoas.',
    'Gosto de brincar de jogos imaginários com as crianças.'
  ]
);

-- Test 3: Perfil Sensorial do Adulto/Adolescente
INSERT INTO testes_templates (nome, sigla, descricao, tipo, versao, faixa_etaria_min, faixa_etaria_max, publico, ativo, configuracao, perguntas)
VALUES (
  'Perfil Sensorial do Adulto/Adolescente',
  'PSA',
  'Perfil Sensorial avaliando processamento tátil/olfativo, movimento, visual, tátil, nível de atividade e processamento auditivo.',
  'escala_likert',
  '1.0',
  12,
  NULL,
  true,
  true,
  '{
    "escala_min": 1,
    "escala_max": 5,
    "opcoes": ["Quase nunca", "Raramente", "Ocasionalmente", "Frequentemente", "Quase sempre"],
    "pontuacao_opcoes": {"1": 1, "2": 2, "3": 3, "4": 4, "5": 5},
    "gabarito": {},
    "interpretacao": {
      "secoes": {
        "processamento_tatil_olfativo": {"itens": [0, 1, 2, 3, 4, 5, 6, 7], "min": 8, "max": 40},
        "processamento_movimento": {"itens": [8, 9, 10, 11, 12, 13, 14, 15], "min": 8, "max": 40},
        "processamento_visual": {"itens": [16, 17, 18, 19, 20, 21, 22, 23, 24, 25], "min": 10, "max": 50},
        "processamento_tatil": {"itens": [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38], "min": 13, "max": 65},
        "nivel_atividade": {"itens": [39, 40, 41, 42, 43, 44, 45, 46, 47, 48], "min": 10, "max": 50},
        "processamento_auditivo": {"itens": [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59], "min": 11, "max": 55}
      },
      "categorias": [
        {"min": 0, "max": 155, "nivel": "Muito Menos", "descricao": "Resposta sensorial muito menor que a maioria"},
        {"min": 156, "max": 216, "nivel": "Menos", "descricao": "Resposta sensorial menor que a maioria"},
        {"min": 217, "max": 233, "nivel": "Normal", "descricao": "Resposta sensorial típica"},
        {"min": 234, "max": 294, "nivel": "Mais", "descricao": "Resposta sensorial maior que a maioria"},
        {"min": 295, "max": 300, "nivel": "Muito Mais", "descricao": "Resposta sensorial muito maior que a maioria"}
      ]
    }
  }'::jsonb,
  ARRAY[
    'Saio ou mudo para outra parte de loja (por ex. produtos para banho, velas, perfumes)',
    'Acrescento temperos na minha comida',
    'Não sinto cheiros que outras pessoas sentem',
    'Gosto de estar próxima a pessoas usando perfume',
    'Só como comidas familiares',
    'Muitas comidas parecem sem sabor para mim (em outras palavras, parece sem graça ou não tem muito sabor)',
    'Não gosto de balas de sabor muito forte (por ex., canela forte ou azedas)',
    'Vou cheirar flores frescas quando as vejo',
    'Tenho medo de alturas',
    'Gosta da sensação de movimento (dançar, correr, por ex.)',
    'Evito elevadores e escadas rolantes porque não gosto de movimento',
    'Tropeço nas coisas',
    'Não gosto do movimento de andar de carro',
    'Escolho me envolver em atividades físicas',
    'Não me sinto muito seguro quando descendo ou subindo escadas (por ex., tropeço, perco o equilíbrio, seguro no corrimão)',
    'Fico tonto facilmente (por ex., após me curvar ou levantar muito rapidamente)',
    'Gosto de ir a lugares com iluminação brilhante e que são coloridos',
    'Mantenho as persianas fechadas durante o dia',
    'Gosto de usar roupa muito colorida',
    'Fico frustrado quando tento encontrar alguma coisa em uma gaveta cheia ou sala bagunçada',
    'Não vejo a rua, prédio, ou placas de salas quando tento ir a um lugar novo',
    'Imagens visuais que se movem rapidamente no cinema ou TV me incomodam',
    'Não noto quando pessoas entram na sala',
    'Escolho fazer compras em lojas menores porque me desoriento em lojas grandes',
    'Incomoda-me quando há muito movimento ao meu redor (por ex. shopping cheio, desfile, parquinho)',
    'Limito as distrações enquanto trabalho (por ex., fecho a porta ou desligo a TV',
    'Não gosto que me esfreguem as costas',
    'Gosto da sensação quando corto o cabelo',
    'Evito ou uso luvas em atividades que vão sujar as minhas mãos',
    'Toco outros enquanto falo (por ex., ponho minha mão em seus ombros ou sacudo suas mãos)',
    'Incomoda-me o modo que sinto minha boca quando acordo',
    'Gosto de andar descalço',
    'Sinto-me mal usando alguns tecidos (por ex, lã, seda, veludo cotelê, etiquetas em roupas',
    'Não gosto de certas texturas de alimentos (por ex., pêssegos com casca, purê de maçã, queijo cottage, pasta de amendoin crocante',
    'Afasto-me quando chegam muito perto de mim',
    'Não pareço notar quando meu rosto e mãos estão sujos',
    'Arranho-me ou tenho marcas roxas mas não me lembro como os fiz',
    'Evito ficar em filas ou ficar próximo a outras pessoas porque não gosto de ficar próximo demais dos outros',
    'Não pareço notar quando alguém toca meu braço ou costas',
    'Trabalho em duas ou mais tarefas ao mesmo tempo',
    'Levo mais tempo que outras pessoas para acordar de manhã',
    'Faço as coisas de improviso (em outras palavras, faço coisas sem planejar antes)',
    'Acho tempo para me afastar da minha vida ocupada e passar tempo sozinho',
    'Pareço mais lenta que outros quando tento seguir uma atividade ou tarefa',
    'Não pego piadas tão rapidamente quanto outros',
    'Afasto-me de multidões',
    'Acho atividades para fazer em frente a outros (por ex., música, esportes, falar em público e responder perguntas em aula',
    'Acho difícil me concentrar por todo o tempo em uma aula ou reunião longos',
    'Evito situações em que possam acontecer coisas inesperadas( por ex, ir a lugares não familiares ou estar perto de pessoas que não conheço',
    'Cantarolo, assobio, canto ou faço outros barulhos',
    'Assusto-me facilmente com sons altos ou inesperados (por ex., aspirador de pó, cachorro latindo, telefone tocando)',
    'Tenho dificuldade em seguir o que as pessoas estão falando quando falam rapidamente ou sobre assuntos não familiares',
    'Saio da sala quando outros assistem TV ou peço a eles que desliguem',
    'Distraio-me se há muito barulho em volta',
    'Não noto quando meu nome é chamado',
    'Uso estratégias para abafar sons (por ex., fecho a porta, cubro os ouvidos, uso protetores de ouvido)',
    'Fico longe de ambientes barulhentos',
    'Gosto de ir a lugares com muita música',
    'Tenho de pedir a pessoas que repitas coisas',
    'Acho difícil trabalhar com barulho de fundo (por ex., ventilador, rádio)'
  ]
);

-- Test 4: ETDAH-AD - Escala de Transtorno de Déficit de Atenção/Hiperatividade
INSERT INTO testes_templates (nome, sigla, descricao, tipo, versao, faixa_etaria_min, faixa_etaria_max, publico, ativo, configuracao, perguntas)
VALUES (
  'ETDAH-AD - Escala de Transtorno de Déficit de Atenção/Hiperatividade',
  'ETDAH-AD',
  'Livro de Aplicação para avaliação de TDAH em adultos com escala de 0 a 5.',
  'escala_likert',
  '1.0',
  18,
  NULL,
  true,
  true,
  '{
    "escala_min": 0,
    "escala_max": 5,
    "opcoes": ["Nunca (0)", "Muito raramente (1)", "Raramente (2)", "Geralmente (3)", "Frequentemente (4)", "Muito Frequentemente (5)"],
    "pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3, "4": 4, "5": 5},
    "gabarito": {},
    "interpretacao": {
      "minimo": 0,
      "maximo": 345,
      "categorias": [
        {"min": 0, "max": 50, "nivel": "Ausente", "descricao": "Sintomas ausentes ou mínimos de TDAH"},
        {"min": 51, "max": 100, "nivel": "Leve", "descricao": "Sintomas leves de TDAH"},
        {"min": 101, "max": 200, "nivel": "Moderado", "descricao": "Sintomas moderados de TDAH"},
        {"min": 201, "max": 345, "nivel": "Grave", "descricao": "Sintomas graves de TDAH"}
      ]
    }
  }'::jsonb,
  ARRAY[
    'É atento quando conversa com alguém.',
    'É afobado no trabalho.',
    'Necessita fazer listas de tudo o que tem para fazer para não se esquecer de nada.',
    'Sente-se chateado e infeliz.',
    'Quando tem de seguir instruções (receitas, montagem de móveis), segue passo a passo e em sequência, tal como lhe é apresentado.',
    'É desorganizado financeiramente.',
    'É solitário.',
    'Termina tudo o que começa.',
    'Explode com facilidade (é do tipo pavio curto).',
    'É detalhista e minucioso.',
    'Arruma encrenca e confusão facilmente.',
    'Mostra-se insensível à dor e ao perigo.',
    'Tem sono agitado, mexe-se na cama.',
    'É bem-aceito por todos.',
    'Costuma se dar mal por falar as coisas sem pensar.',
    'É persistente e insistente diante de uma ideia.',
    'Acidenta-se com facilidade (cai, tropeça, esbarra em móveis).',
    'Tende a discordar das regras e normas.',
    'Dá impressão de que não sabe o que quer.',
    'Evita trabalhos longos, detalhados e complicados.',
    'Tem dificuldade para se adaptar às mudanças.',
    'A qualidade do trabalho é comprometida porque não presta atenção suficiente.',
    'Inicia uma atividade com entusiasmo e dificilmente chega ao fim, é do tipo fogo de palha.',
    'Evita as atividades que exijam esforço mental prolongado (p. ex., leitura, filmes).',
    'Perde a paciência com os familiares.',
    'É rebelde com as pessoas e as situações.',
    'Persiste quando quer alguma coisa.',
    'Tem tendência a sonhar acordado.',
    'Faz planos cuidadosamente, considera todos os passos do começo ao fim.',
    'Parece sonhar acordado.',
    'Faz seu trabalho rápido demais.',
    'É distraído com tudo.',
    'Dificilmente chega ao final de um projeto.',
    'Seu hábito de trabalho é confuso e desorganizado.',
    'Necessita estar em constante movimentação.'
  ]
);

-- Test 5: BHS - Escala de Desesperança de Beck
INSERT INTO testes_templates (nome, sigla, descricao, tipo, versao, faixa_etaria_min, faixa_etaria_max, publico, ativo, configuracao, perguntas)
VALUES (
  'BHS - Escala de Desesperança de Beck',
  'BHS',
  'Este questionário consiste em 20 afirmações. Por favor, leia as afirmações cuidadosamente, uma por uma. Se a afirmação descreve a sua atitude na última semana, incluindo hoje, marque C (CERTO). Se não descreve, marque E (ERRADO).',
  'multipla_escolha',
  '1.0',
  12,
  NULL,
  true,
  true,
  '{
    "opcoes": ["Certo", "Errado"],
    "gabarito": {
      "0": {"resposta_correta": "Errado", "pontuacao": 1},
      "1": {"resposta_correta": "Certo", "pontuacao": 1},
      "2": {"resposta_correta": "Errado", "pontuacao": 1},
      "3": {"resposta_correta": "Certo", "pontuacao": 1},
      "4": {"resposta_correta": "Errado", "pontuacao": 1},
      "5": {"resposta_correta": "Errado", "pontuacao": 1},
      "6": {"resposta_correta": "Certo", "pontuacao": 1},
      "7": {"resposta_correta": "Errado", "pontuacao": 1},
      "8": {"resposta_correta": "Certo", "pontuacao": 1},
      "9": {"resposta_correta": "Errado", "pontuacao": 1},
      "10": {"resposta_correta": "Certo", "pontuacao": 1},
      "11": {"resposta_correta": "Certo", "pontuacao": 1},
      "12": {"resposta_correta": "Errado", "pontuacao": 1},
      "13": {"resposta_correta": "Certo", "pontuacao": 1},
      "14": {"resposta_correta": "Errado", "pontuacao": 1},
      "15": {"resposta_correta": "Certo", "pontuacao": 1},
      "16": {"resposta_correta": "Certo", "pontuacao": 1},
      "17": {"resposta_correta": "Certo", "pontuacao": 1},
      "18": {"resposta_correta": "Errado", "pontuacao": 1},
      "19": {"resposta_correta": "Certo", "pontuacao": 1}
    }
  }'::jsonb,
  ARRAY[
    'Penso no futuro com esperança e entusiasmo.',
    'Seria melhor desistir, porque nada há que eu possa fazer para tornar as coisas melhores para mim.',
    'Quando as coisas vão mal, me ajuda saber que elas não podem continuar assim para sempre.',
    'Não consigo imaginar que espécie de vida será a minha em dez anos.',
    'Tenho tempo suficiente para realizar as coisas que quero fazer.',
    'No futuro, eu espero ter sucesso no que mais me interessa.',
    'Meu futuro me parece negro.',
    'Acontece que tenho uma sorte especial e espero conseguir mais coisas boas da vida do que uma pessoa comum.',
    'Simplesmente não consigo aproveitar as oportunidades e não há razão para que consiga, no futuro.',
    'Minhas experiências passadas me prepararam bem para o futuro.',
    'Tudo o que posso ver à minha frente é mais desprazer do que prazer.',
    'Não espero conseguir o que realmente quero.',
    'Quando penso no futuro, espero ser mais feliz do que sou agora.',
    'As coisas simplesmente não se resolvem da maneira que eu quero.',
    'Tenho uma grande fé no futuro.',
    'Nunca consigo o que quero. Assim, é tolice querer qualquer coisa.',
    'É pouco provável que eu vá obter qualquer satisfação real, no futuro.',
    'O futuro me parece vago e incerto.',
    'Posso esperar mais tempos bons do que maus.',
    'Não adianta tentar realmente obter algo que quero, porque provavelmente não vou conseguir.'
  ]
);

-- Test 6: SRS-2 - Escala de Responsividade Social
INSERT INTO testes_templates (nome, sigla, descricao, tipo, versao, faixa_etaria_min, faixa_etaria_max, publico, ativo, configuracao, perguntas)
VALUES (
  'SRS-2 - Escala de Responsividade Social',
  'SRS-2',
  'Formulário Adulto Autorrelato para avaliação de comportamentos sociais. Em cada questão, por favor preencha o círculo que melhor descreve o seu comportamento nos últimos 6 meses.',
  'escala_likert',
  '2.0',
  19,
  NULL,
  true,
  true,
  '{
    "escala_min": 1,
    "escala_max": 4,
    "opcoes": ["Não é verdade", "Algumas vezes é verdade", "Muitas vezes é verdade", "Quase sempre é verdade"],
    "pontuacao_opcoes": {"1": 1, "2": 2, "3": 3, "4": 4},
    "gabarito": {},
    "interpretacao": {
      "minimo": 28,
      "maximo": 112,
      "categorias": [
        {"min": 28, "max": 43, "nivel": "Normal", "descricao": "Funcionamento social dentro da média"},
        {"min": 44, "max": 59, "nivel": "Leve", "descricao": "Dificuldades sociais leves"},
        {"min": 60, "max": 75, "nivel": "Moderado", "descricao": "Dificuldades sociais moderadas"},
        {"min": 76, "max": 112, "nivel": "Grave", "descricao": "Dificuldades sociais graves"}
      ]
    }
  }'::jsonb,
  ARRAY[
    'Eu fico muito mais desconfortável em situações sociais do que quando estou sozinho.',
    'Minhas expressões faciais passam uma mensagem errada aos outros sobre como eu realmente me sinto.',
    'Eu me sinto confiante (ou seguro) quando estou interagindo com os outros.',
    'Quando estou sob estresse, tenho um comportamento rígido e inflexível que parece estranho para os outros.',
    'Eu não reconheço quando os outros estão tentando tirar vantagem sobre mim.',
    'Eu preferia estar sozinho do que com os outros.',
    'Normalmente eu consigo perceber como os outros estão se sentindo.',
    'Eu me comporto de maneiras que parecem estranhas ou esquisitas aos outros.',
    'Eu sou excessivamente dependente dos outros para me ajudar entender as minhas necessidades diárias.',
    'Eu levo as coisas muito "ao pé da letra", e por causa disso, eu interpreto mal o significado pretendido de partes de uma conversa.',
    'Eu sou autoconfiante.',
    'Eu sou capaz de comunicar meus sentimentos aos outros.',
    'Eu fico estranho nas interações com os colegas (por exemplo, eu levo um tempo acompanhando o vai e vem da conversa).',
    'Eu não sou bem coordenado.',
    'Quando as pessoas mudam seu tom ou expressão facial, eu normalmente entendo o que isso significa.',
    'Eu evito contato visual ou me dizem que eu tenho contato visual diferente.',
    'Eu reconheço quando algo é injusto.',
    'Eu tenho dificuldade em fazer amigos, mesmo quando eu tento dar o melhor de mim.',
    'Eu fico frustrado tentando expressar minhas ideias em uma conversa.',
    'Eu tenho interesses sensoriais que os outros acham diferentes (por exemplo, cheirar ou olhar para as coisas de um jeito especial).',
    'Eu sou capaz de imitar a ação e expressão dos outros quando é socialmente apropriado.',
    'Eu interajo apropriadamente com os outros adultos.',
    'Eu não participo de atividades em grupo ou eventos sociais a menos que seja obrigado fazê-lo.',
    'Eu tenho mais dificuldade que os outros com mudanças na minha rotina.',
    'Eu não me importo de não estar "na mesma onda" ou fora de sintonia com os outros.',
    'Eu ofereço conforto aos outros quando eles estão tristes.',
    'Eu evito iniciar interações sociais com outros adultos.',
    'Eu penso ou falo sobre a mesma coisa repetidamente.'
  ]
);

-- Test 7: BDEFS - Barkley Deficits in Executive Functioning Scale
INSERT INTO testes_templates (nome, sigla, descricao, tipo, versao, faixa_etaria_min, faixa_etaria_max, publico, ativo, configuracao, perguntas)
VALUES (
  'BDEFS - Barkley Deficits in Executive Functioning Scale',
  'BDEFS',
  'Folha de resposta - Versão Longa. Com que frequência você passa por cada um desses problemas? Por favor, ignore as seções nomeadas como "para uso do examinador".',
  'escala_likert',
  '1.0',
  18,
  NULL,
  true,
  true,
  '{
    "escala_min": 1,
    "escala_max": 4,
    "opcoes": ["Raramente ou nunca", "Às vezes", "Frequentemente", "Muito frequentemente"],
    "pontuacao_opcoes": {"1": 1, "2": 2, "3": 3, "4": 4},
    "gabarito": {},
    "interpretacao": {
      "secoes": {
        "secao_1": {"itens": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], "min": 21, "max": 84, "nome": "Gestão do Tempo"},
        "secao_2": {"itens": [21, 22, 23, 24, 25, 26, 27, 28, 29], "min": 9, "max": 36, "nome": "Organização/Resolução de Problemas"},
        "secao_3": {"itens": [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44], "min": 15, "max": 60, "nome": "Autocontrole"},
        "secao_4": {"itens": [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63], "min": 19, "max": 76, "nome": "Automotivação"},
        "secao_5": {"itens": [64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88], "min": 25, "max": 100, "nome": "Autorregulação Emocional"}
      },
      "minimo": 89,
      "maximo": 356,
      "categorias": [
        {"min": 89, "max": 130, "nivel": "Normal", "descricao": "Funcionamento executivo adequado"},
        {"min": 131, "max": 180, "nivel": "Leve", "descricao": "Déficits leves em funções executivas"},
        {"min": 181, "max": 270, "nivel": "Moderado", "descricao": "Déficits moderados em funções executivas"},
        {"min": 271, "max": 356, "nivel": "Grave", "descricao": "Déficits graves em funções executivas"}
      ]
    }
  }'::jsonb,
  ARRAY[
    'Procrastino ou adio fazer as coisas até o último minuto.',
    'Tenho pouca noção de tempo.',
    'Desperdiço ou administro mal o meu tempo.',
    'Sou despreparado para trabalhos ou tarefas a mim atribuídas.',
    'Não cumpro os prazos das tarefas.',
    'Tenho problemas para planejar com antecedência ou para me preparar para eventos futuros.',
    'Esqueço de fazer coisas que deveria fazer.',
    'Parece que eu não consigo cumprir as metas que estabeleço para mim mesmo.',
    'Me atraso para o trabalho ou compromissos agendados.',
    'Parece que eu não consigo manter em mente coisas das quais preciso me lembrar de fazer.',
    'Parece que eu não consigo finalizar as coisas, a menos que tenham um prazo final imediato.',
    'Tenho dificuldade em julgar quanto tempo irei gastar para fazer algo ou para ir a algum lugar.',
    'Tenho dificuldades em me motivar para começar a trabalhar.',
    'Tenho dificuldade para me motivar a continuar com o meu trabalho e terminá-lo.',
    'Fico desmotivado para me preparar com antecedência para coisas que devo fazer.',
    'Tenho problemas em completar uma atividade antes de iniciar uma nova.',
    'Tenho dificuldades em fazer aquilo que eu digo a mim mesmo para fazer.',
    'Tenho dificuldades em cumprir as promessas ou compromissos que eu possa ter assumido com outras pessoas.',
    'Tenho falta de auto-disciplina.',
    'Tenho dificuldades em me organizar ou em fazer meu trabalho de acordo com sua prioridade ou importância; não consigo "priorizar" bem.',
    'Acho difícil começar ou continuar a fazer coisas que preciso terminar.',
    'Parece que eu não consigo me lembrar do que ouvi ou li anteriormente.',
    'Parece que eu não consigo me lembrar de coisas, mesmo quando me apresentam coisas complicadas de se fazer.',
    'Tenho dificuldades em organizar meus pensamentos.',
    'Quando me apresentam coisas complicadas de se fazer, eu não consigo manter as informações na cabeça para fazer igual ou fazer melhor.',
    'Tenho problemas quando preciso avaliar várias opções para fazer as coisas e ponderar as suas consequências.',
    'Tenho dificuldades para dizer o que eu quero dizer.',
    'Sou incapaz de criar ou inventar tantas soluções para problemas quanto os outros.',
    'As palavras parecem me faltar quando quero explicar alguma coisa para os outros.',
    'Tenho dificuldade em expressar meus pensamentos por escrito tão bem ou tão rapidamente quanto os outros.',
    'Sinto que não sou tão criativo ou inventivo quanto os outros com o mesmo nível de inteligência.',
    'Quando tento cumprir metas ou compromissos, não me acho capaz de pensar em tantas maneiras de fazer as coisas como os outros.',
    'Tenho dificuldade em aprender atividades novas e complexas tão bem como os outros.',
    'Tenho dificuldade em explicar as coisas na ordem ou sequência apropriada.',
    'Não consigo concluir minhas explicações tão rapidamente quanto os outros.',
    'Tenho dificuldades em fazer as coisas na ordem ou sequência apropriada.',
    'Sou incapaz de pensar e reagir rapidamente ou de modo tão eficiente quanto outras pessoas quando ocorrem eventos inesperados.',
    'Eu sou mais lento do que outros para resolver problemas que encontro no meu dia a dia.',
    'Fico facilmente distraído por pensamentos irrelevantes quando eu tenho que me concentrar em algo.',
    'Sou incapaz de entender o que leio tão bem quanto eu deveria. Tenho que reler o material para entender seu significado.',
    'Não consigo focar minha atenção em tarefas ou no trabalho tão bem quanto os outros.',
    'Fico facilmente confuso.',
    'Não consigo manter a minha concentração na leitura, em formulários, em palestras ou no trabalho.',
    'Acho difícil focar no que é importante diante do que não é importante quando estou fazendo alguma coisa.',
    'Parece que eu não consigo processar informações de modo tão rápido ou preciso quanto os outros.',
    'Acho difícil tolerar esperas; impaciente.',
    'Tomo decisões impulsivamente.',
    'Sou incapaz de inibir minhas reações ou respostas a situações ou aos outros.',
    'Tenho dificuldade em parar minhas atividades ou comportamento quando deveria.',
    'Tenho dificuldade em mudar meu comportamento quando me falam sobre os meus erros.',
    'Faço comentários impulsivos para os outros.',
    'Sou propenso a fazer coisas sem considerar as consequências.',
    'Mudo meus planos no último minuto por um capricho ou impulso de último minuto.',
    'Não levo em consideração fatos relevantes do passado ou experiências passadas antes de responder às situações (Eu ajo sem pensar).',
    'Não tenho consciência das coisas que eu falo ou faço.',
    'Tenho dificuldade em ser objetivo com as coisas que mexem comigo.',
    'Acho difícil assumir as perspectivas de outras pessoas sobre um problema ou uma situação.',
    'Não penso nem falo as coisas comigo mesmo antes de fazer algo.',
    'Tenho dificuldade para seguir as regras em uma situação.',
    'Tenho tendência a dirigir mais rápido que os outros (velocidade excessiva).',
    'Não tolero muito bem situações frustrantes.',
    'Não consigo inibir minhas emoções tão bem quanto os outros.',
    'Não olho para frente e não penso sobre quais serão os resultados futuros antes de fazer alguma coisa (Não faço previsões).',
    'Eu me envolvo em atividades de risco mais do que os outros estão propensos a fazer.'
  ]
);

-- Test 8: BDI-II - Inventário de Depressão de Beck
INSERT INTO testes_templates (nome, sigla, descricao, tipo, versao, faixa_etaria_min, faixa_etaria_max, publico, ativo, configuracao, perguntas)
VALUES (
  'BDI-II - Inventário de Depressão de Beck',
  'BDI-II',
  'Este questionário consiste em 21 grupos de afirmações. Por favor, leia cada uma delas cuidadosamente. Depois, escolha uma frase de cada grupo, que melhor descreva a maneira como você tem se sentido nas duas últimas semanas, incluindo o dia de hoje.',
  'multipla_escolha',
  '2.0',
  13,
  NULL,
  true,
  true,
  '{
    "opcoes_por_pergunta": true,
    "gabarito": {
      "0": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "1": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "2": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "3": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "4": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "5": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "6": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "7": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "8": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "9": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "10": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "11": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "12": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "13": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "14": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "15": {"pontuacao_opcoes": {"0": 0, "1a": 1, "1b": 1, "2a": 2, "2b": 2, "3a": 3, "3b": 3}},
      "16": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "17": {"pontuacao_opcoes": {"0": 0, "1a": 1, "1b": 1, "2a": 2, "2b": 2, "3a": 3, "3b": 3}},
      "18": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "19": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}},
      "20": {"pontuacao_opcoes": {"0": 0, "1": 1, "2": 2, "3": 3}}
    },
    "interpretacao": {
      "minimo": 0,
      "maximo": 63,
      "categorias": [
        {"min": 0, "max": 13, "nivel": "Mínimo", "descricao": "Depressão mínima ou ausente"},
        {"min": 14, "max": 19, "nivel": "Leve", "descricao": "Depressão leve"},
        {"min": 20, "max": 28, "nivel": "Moderado", "descricao": "Depressão moderada"},
        {"min": 29, "max": 63, "nivel": "Grave", "descricao": "Depressão grave"}
      ]
    }
  }'::jsonb,
  ARRAY[
    'Tristeza',
    'Pessimismo',
    'Fracasso passado',
    'Perda de prazer',
    'Sentimentos de culpa',
    'Sentimentos de punição',
    'Auto-estima',
    'Autocrítica',
    'Pensamentos ou desejos suicidas',
    'Choro',
    'Agitação',
    'Perda de interesse',
    'Indecisão',
    'Desvalorização',
    'Falta de energia',
    'Alterações no padrão de sono',
    'Irritabilidade',
    'Alterações de apetite',
    'Dificuldade de concentração',
    'Cansaço ou fadiga',
    'Perda de interesse por sexo'
  ]
);

-- =====================================================
-- END OF SEED SCRIPT
-- =====================================================
-- Summary:
-- - 8 neuropsychological assessment tests inserted
-- - Total of 430+ questions across all tests
-- - Tests include: EPF-TDAH, AQ, PSA, ETDAH-AD, BHS, SRS-2, BDEFS, BDI-II
-- =====================================================
